# Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Import Dataset

In [2]:
dataset=pd.read_csv(r'readmission.csv')
dataset

encounter_id  patient_nbr             race  gender      age weight  \
0            2278392      8222157        Caucasian  Female   [0-10)      ?   
1             149190     55629189        Caucasian  Female  [10-20)      ?   
2              64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3             500364     82442376        Caucasian    Male  [30-40)      ?   
4              16680     42519267        Caucasian    Male  [40-50)      ?   
...              ...          ...              ...     ...      ...    ...   
101761     443847548    100162476  AfricanAmerican    Male  [70-80)      ?   
101762     443847782     74694222  AfricanAmerican  Female  [80-90)      ?   
101763     443854148     41088789        Caucasian    Male  [70-80)      ?   
101764     443857166     31693671        Caucasian  Female  [80-90)      ?   
101765     443867222    175429310        Caucasian    Male  [70-80)      ?   

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1   
1                       1                         1                    7   
2                       1                         1                    7   
3                       1                         1                    7   
4                       1                         1                    7   
...                   ...                       ...                  ...   
101761                  1                         3                    7   
101762                  1                         4                    5   
101763                  1                         1                    7   
101764                  2                         3                    7   
101765                  1                         1                    7   

        time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                      1  ...          No      No                   No   
1                      3  ...          No      Up                   No   
2                      2  ...          No      No                   No   
3                      2  ...          No      Up                   No   
4                      1  ...          No  Steady                   No   
...                  ...  ...         ...     ...                  ...   
101761                 3  ...          No    Down                   No   
101762                 5  ...          No  Steady                   No   
101763                 1  ...          No    Down                   No   
101764                10  ...          No      Up                   No   
101765                 6  ...          No      No                   No   

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No   
1                        No                        No   
2                        No                        No   
3                        No                        No   
4                        No                        No   
...                     ...                       ...   
101761                   No                        No   
101762                   No                        No   
101763                   No                        No   
101764                   No                        No   
101765                   No                        No   

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No   
1                            No                      No      Ch         Yes   
2                            No                      No      No         Yes   
3                            No                      No      Ch         Yes   
4                            No                      No      Ch         Yes   
...                         ...                     ...     ...         ...   
101761                       No

# Data Visualization

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any().any()

False

In [5]:
dataset.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
encounter_id                101766 non-null int64
patient_nbr                 101766 non-null int64
race                        101766 non-null object
gender                      101766 non-null object
age                         101766 non-null object
weight                      101766 non-null object
admission_type_id           101766 non-null int64
discharge_disposition_id    101766 non-null int64
admission_source_id         101766 non-null int64
time_in_hospital            101766 non-null int64
payer_code                  101766 non-null object
medical_specialty           101766 non-null object
num_lab_procedures          101766 non-null int64
num_procedures              101766 non-null int64
num_medications             101766 non-null int64
number_outpatient           101766 non-null int64
number_emergency            101766 non-null int64
number_inpatient            10176

In [7]:
dataset.groupby('readmitted').size()

readmitted
<30    11357
>30    35545
NO     54864
dtype: int64

In [8]:
dataset.describe()

encounter_id   patient_nbr  admission_type_id  \
count  1.017660e+05  1.017660e+05      101766.000000   
mean   1.652016e+08  5.433040e+07           2.024006   
std    1.026403e+08  3.869636e+07           1.445403   
min    1.252200e+04  1.350000e+02           1.000000   
25%    8.496119e+07  2.341322e+07           1.000000   
50%    1.523890e+08  4.550514e+07           1.000000   
75%    2.302709e+08  8.754595e+07           3.000000   
max    4.438672e+08  1.895026e+08           8.000000   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
count             101766.000000        101766.000000     101766.000000   
mean                   3.715642             5.754437          4.395987   
std                    5.280166             4.064081          2.985108   
min                    1.000000             1.000000          1.000000   
25%                    1.000000             1.000000          2.000000   
50%                    1.000000             7.000000          4.000000   
75%                    4.000000             7.000000          6.000000   
max                   28.000000            25.000000         14.000000   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
count       101766.000000   101766.000000    101766.000000      101766.000000   
mean            43.095641        1.339730        16.021844           0.369357   
std             19.674362        1.705807         8.127566           1.267265   
min              1.000000        0.000000         1.000000           0.000000   
25%             31.000000        0.000000        10.000000           0.000000   
50%             44.000000        1.000000        15.000000           0.000000   
75%             57.000000        2.000000        20.000000           0.000000   
max            132.000000        6.000000        81.000000          42.000000   

       number_emergency  number_inpatient  number_diagnoses  
count     101766.000000     101766.000000     101766.000000  
mean           0.197836          0.635566          7.422607  
std            0.930472          1.262863          1.933600  
min            0.000000          0.000000          1.000000  
25%            0.000000          0.000000          6.000000  
50%            0.000000          0.000000          8.000000  
75%            0.000000          1.000000          9.000000  
max           76.000000         21.000000         16.000000

In [9]:
# for each column
for c in list(dataset.columns):
    
    # get a list of unique values
    n = dataset[c].unique()
    
    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(n)<30:
        print(c)
        print(n)
    else:
        print(c + ': ' +str(len(n)) + ' unique values')

encounter_id: 101766 unique values
patient_nbr: 71518 unique values
race
['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']
gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
weight
['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)' '[25-50)' '[125-150)'
 '[175-200)' '[150-175)' '>200']
admission_type_id
[6 1 2 3 4 5 8 7]
discharge_disposition_id
[25  1  3  6  2  5 11  7 10  4 14 18  8 13 12 16 17 22 23  9 20 15 24 28
 19 27]
admission_source_id
[ 1  7  2  4  5  6 20  3 17  8  9 14 10 22 11 25 13]
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
payer_code
['?' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM' 'CM' 'CH' 'PO' 'WC' 'OT'
 'OG' 'MP' 'FR']
medical_specialty: 73 unique values
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient

# Taking Care Of Missing Data

In [10]:
#We shall remove some unwanted columns from our dataset

In [11]:
dataset.groupby('examide').size()

examide
No    101766
dtype: int64

In [12]:
dataset.groupby('citoglipton').size()

citoglipton
No    101766
dtype: int64

In [13]:
dataset.drop(['patient_nbr','encounter_id','race','examide','citoglipton',],axis=1,inplace=True)

In [14]:
dataset

gender      age weight  admission_type_id  discharge_disposition_id  \
0       Female   [0-10)      ?                  6                        25   
1       Female  [10-20)      ?                  1                         1   
2       Female  [20-30)      ?                  1                         1   
3         Male  [30-40)      ?                  1                         1   
4         Male  [40-50)      ?                  1                         1   
...        ...      ...    ...                ...                       ...   
101761    Male  [70-80)      ?                  1                         3   
101762  Female  [80-90)      ?                  1                         4   
101763    Male  [70-80)      ?                  1                         1   
101764  Female  [80-90)      ?                  2                         3   
101765    Male  [70-80)      ?                  1                         1   

        admission_source_id  time_in_hospital payer_code  \
0                         1                 1          ?   
1                         7                 3          ?   
2                         7                 2          ?   
3                         7                 2          ?   
4                         7                 1          ?   
...                     ...               ...        ...   
101761                    7                 3         MC   
101762                    5                 5         MC   
101763                    7                 1         MC   
101764                    7                10         MC   
101765                    7                 6          ?   

               medical_specialty  num_lab_procedures  ...  tolazamide  \
0       Pediatrics-Endocrinology                  41  ...          No   
1                              ?                  59  ...          No   
2                              ?                  11  ...          No   
3                              ?                  44  ...          No   
4                              ?                  51  ...          No   
...                          ...                 ...  ...         ...   
101761                         ?                  51  ...          No   
101762                         ?                  33  ...          No   
101763                         ?                  53  ...          No   
101764           Surgery-General                  45  ...          No   
101765                         ?                  13  ...          No   

        insulin  glyburide-metformin  glipizide-metformin  \
0            No                   No                   No   
1            Up                   No                   No   
2            No                   No                   No   
3            Up                   No                   No   
4        Steady                   No                   No   
...         ...                  ...                  ...   
101761     Down                   No                   No   
101762   Steady                   No                   No   
101763     Down                   No                   No   
101764       Up                   No                   No   
101765       No                   No                   No   

        glimepiride-pioglitazone metformin-rosiglitazone  \
0                             No                      No   
1                             No                      No   
2                             No                      No   
3                             No                      No   
4                             No                      No   
...                          ...                     ...   
101761                        No                      No   
101762                        No                      No   
101763                        No                      No   
101764                        No                      No   
101765                        No                      No   

       

In [15]:
#if we look at data discription we know that 11,13,14,19,20,21 are related to death or hospice. 
#We should remove these samples from the predictive model.

In [16]:
dataset = dataset.loc[~dataset.discharge_disposition_id.isin([11,13,14,19,20,21])]
dataset.groupby('discharge_disposition_id').size()

discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
12        3
15       63
16       11
17       14
18     3691
22     1993
23      412
24       48
25      989
27        5
28      139
dtype: int64

In [17]:
dataset

gender      age weight  admission_type_id  discharge_disposition_id  \
0       Female   [0-10)      ?                  6                        25   
1       Female  [10-20)      ?                  1                         1   
2       Female  [20-30)      ?                  1                         1   
3         Male  [30-40)      ?                  1                         1   
4         Male  [40-50)      ?                  1                         1   
...        ...      ...    ...                ...                       ...   
101761    Male  [70-80)      ?                  1                         3   
101762  Female  [80-90)      ?                  1                         4   
101763    Male  [70-80)      ?                  1                         1   
101764  Female  [80-90)      ?                  2                         3   
101765    Male  [70-80)      ?                  1                         1   

        admission_source_id  time_in_hospital payer_code  \
0                         1                 1          ?   
1                         7                 3          ?   
2                         7                 2          ?   
3                         7                 2          ?   
4                         7                 1          ?   
...                     ...               ...        ...   
101761                    7                 3         MC   
101762                    5                 5         MC   
101763                    7                 1         MC   
101764                    7                10         MC   
101765                    7                 6          ?   

               medical_specialty  num_lab_procedures  ...  tolazamide  \
0       Pediatrics-Endocrinology                  41  ...          No   
1                              ?                  59  ...          No   
2                              ?                  11  ...          No   
3                              ?                  44  ...          No   
4                              ?                  51  ...          No   
...                          ...                 ...  ...         ...   
101761                         ?                  51  ...          No   
101762                         ?                  33  ...          No   
101763                         ?                  53  ...          No   
101764           Surgery-General                  45  ...          No   
101765                         ?                  13  ...          No   

        insulin  glyburide-metformin  glipizide-metformin  \
0            No                   No                   No   
1            Up                   No                   No   
2            No                   No                   No   
3            Up                   No                   No   
4        Steady                   No                   No   
...         ...                  ...                  ...   
101761     Down                   No                   No   
101762   Steady                   No                   No   
101763     Down                   No                   No   
101764       Up                   No                   No   
101765       No                   No                   No   

        glimepiride-pioglitazone metformin-rosiglitazone  \
0                             No                      No   
1                             No                      No   
2                             No                      No   
3                             No                      No   
4                             No                      No   
...                          ...                     ...   
101761                        No                      No   
101762                        No                      No   
101763                        No                      No   
101764                        No                      No   
101765                        No                      No   

       

In [18]:
#Now we will examine numerical data

In [19]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']
dataset[cols_num].isnull().sum()

time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
dtype: int64

In [20]:
#Now examining and handling categorical data

In [21]:
# replace ? with nan
dataset=dataset.replace('?',np.nan)
dataset

gender      age weight  admission_type_id  discharge_disposition_id  \
0       Female   [0-10)    NaN                  6                        25   
1       Female  [10-20)    NaN                  1                         1   
2       Female  [20-30)    NaN                  1                         1   
3         Male  [30-40)    NaN                  1                         1   
4         Male  [40-50)    NaN                  1                         1   
...        ...      ...    ...                ...                       ...   
101761    Male  [70-80)    NaN                  1                         3   
101762  Female  [80-90)    NaN                  1                         4   
101763    Male  [70-80)    NaN                  1                         1   
101764  Female  [80-90)    NaN                  2                         3   
101765    Male  [70-80)    NaN                  1                         1   

        admission_source_id  time_in_hospital payer_code  \
0                         1                 1        NaN   
1                         7                 3        NaN   
2                         7                 2        NaN   
3                         7                 2        NaN   
4                         7                 1        NaN   
...                     ...               ...        ...   
101761                    7                 3         MC   
101762                    5                 5         MC   
101763                    7                 1         MC   
101764                    7                10         MC   
101765                    7                 6        NaN   

               medical_specialty  num_lab_procedures  ...  tolazamide  \
0       Pediatrics-Endocrinology                  41  ...          No   
1                            NaN                  59  ...          No   
2                            NaN                  11  ...          No   
3                            NaN                  44  ...          No   
4                            NaN                  51  ...          No   
...                          ...                 ...  ...         ...   
101761                       NaN                  51  ...          No   
101762                       NaN                  33  ...          No   
101763                       NaN                  53  ...          No   
101764           Surgery-General                  45  ...          No   
101765                       NaN                  13  ...          No   

        insulin  glyburide-metformin  glipizide-metformin  \
0            No                   No                   No   
1            Up                   No                   No   
2            No                   No                   No   
3            Up                   No                   No   
4        Steady                   No                   No   
...         ...                  ...                  ...   
101761     Down                   No                   No   
101762   Steady                   No                   No   
101763     Down                   No                   No   
101764       Up                   No                   No   
101765       No                   No                   No   

        glimepiride-pioglitazone metformin-rosiglitazone  \
0                             No                      No   
1                             No                      No   
2                             No                      No   
3                             No                      No   
4                             No                      No   
...                          ...                     ...   
101761                        No                      No   
101762                        No                      No   
101763                        No                      No   
101764                        No                      No   
101765                        No                      No   

       

In [22]:
dataset.isnull().any()

gender                      False
age                         False
weight                       True
admission_type_id           False
discharge_disposition_id    False
admission_source_id         False
time_in_hospital            False
payer_code                   True
medical_specialty            True
num_lab_procedures          False
num_procedures              False
num_medications             False
number_outpatient           False
number_emergency            False
number_inpatient            False
diag_1                       True
diag_2                       True
diag_3                       True
number_diagnoses            False
max_glu_serum               False
A1Cresult                   False
metformin                   False
repaglinide                 False
nateglinide                 False
chlorpropamide              False
glimepiride                 False
acetohexamide               False
glipizide                   False
glyburide                   False
tolbutamide   

In [23]:
#There are some string values in columns diag_1 diag_2 and diag_3

dataset['diag_1'] = dataset['diag_1'].str.extract('(\d+)').astype(float)

In [24]:
dataset['diag_2'] = dataset['diag_2'].str.extract('(\d+)').astype(float)
dataset['diag_3'] = dataset['diag_3'].str.extract('(\d+)').astype(float)

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99343 entries, 0 to 101765
Data columns (total 45 columns):
gender                      99343 non-null object
age                         99343 non-null object
weight                      3125 non-null object
admission_type_id           99343 non-null int64
discharge_disposition_id    99343 non-null int64
admission_source_id         99343 non-null int64
time_in_hospital            99343 non-null int64
payer_code                  59945 non-null object
medical_specialty           50727 non-null object
num_lab_procedures          99343 non-null int64
num_procedures              99343 non-null int64
num_medications             99343 non-null int64
number_outpatient           99343 non-null int64
number_emergency            99343 non-null int64
number_inpatient            99343 non-null int64
diag_1                      99323 non-null float64
diag_2                      98987 non-null float64
diag_3                      97924 non-null float6

In [26]:
dataset['age'] = dataset['age'].fillna('UNK')
dataset['weight'] = dataset['weight'].fillna('UNK')
dataset['payer_code'] = dataset['payer_code'].fillna('UNK')
dataset['medical_specialty'] = dataset['medical_specialty'].fillna('UNK')

In [27]:
dataset['diag_1'].mean()

488.325755363813

In [28]:
dataset['diag_1'] = dataset['diag_1'].fillna(dataset['diag_1'].mean())

In [29]:
dataset['diag_2'] = dataset['diag_2'].fillna(dataset['diag_2'].mean())
dataset['diag_3'] = dataset['diag_3'].fillna(dataset['diag_3'].mean())

In [30]:
dataset.isnull().any().any()

False

In [31]:
#We shall examine medical_speciality column

In [32]:
print('Number medical specialty:', dataset.medical_specialty.nunique())
dataset.groupby('medical_specialty').size().sort_values(ascending = False)

Number medical specialty: 73


medical_specialty
UNK                                 48616
InternalMedicine                    14237
Emergency/Trauma                     7419
Family/GeneralPractice               7252
Cardiology                           5279
                                    ...  
Psychiatry-Addictive                    1
Dermatology                             1
Speech                                  1
SportsMedicine                          1
Surgery-PlasticwithinHeadandNeck        1
Length: 73, dtype: int64

In [33]:
#Here we can see that there are 73 types of categorical variables, we shall narrow them down to less types 

In [34]:
top_10 = ['UNK','InternalMedicine','Emergency/Trauma',\
          'Family/GeneralPractice', 'Cardiology','Surgery-General' ,\
          'Nephrology','Orthopedics',\
          'Orthopedics-Reconstructive','Radiologist']

# make a new column with duplicated data
dataset['med_spec'] = dataset['medical_specialty'].copy()

# replace all specialties not in top 10 with 'Other' category
dataset.loc[~dataset.med_spec.isin(top_10),'med_spec'] = 'Other'

In [35]:
dataset.groupby('med_spec').size()

med_spec
Cardiology                     5279
Emergency/Trauma               7419
Family/GeneralPractice         7252
InternalMedicine              14237
Nephrology                     1539
Orthopedics                    1392
Orthopedics-Reconstructive     1230
Other                          8199
Radiologist                    1121
Surgery-General                3059
UNK                           48616
dtype: int64

In [36]:
#Now we shall remove the medical_speciality column 

In [37]:
dataset.drop("medical_specialty",axis=1,inplace=True)

In [38]:
#Similarly lets deduce only two results from the last column readmitted

In [39]:
dataset.groupby('readmitted').size()

readmitted
<30    11314
>30    35502
NO     52527
dtype: int64

In [40]:
col = ['<30','>30']

# make a new column with duplicated data
dataset['readmitted_final'] = dataset['readmitted'].copy()

# replace all specialties not in top 10 with 'Other' category
dataset.loc[dataset.readmitted_final.isin(col),'readmitted_final'] = 'YES'

In [41]:
dataset.groupby('readmitted_final').size()

readmitted_final
NO     52527
YES    46816
dtype: int64

In [42]:
dataset.drop("readmitted",axis=1,inplace=True)
dataset.columns

Index(['gender', 'age', 'weight', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'med_spec',
       'readmitted_final'],
      dtype='object')

In [43]:
dataset.groupby('weight').size()

weight
>200             3
UNK          96218
[0-25)          48
[100-125)      617
[125-150)      143
[150-175)       34
[175-200)       11
[25-50)         90
[50-75)        867
[75-100)      1312
dtype: int64

In [44]:
#Seeing the ratio of known and unkown data, if we keep the weight column we may end up getting unwanted results, 
#So, it is better to drop the weight column as well according to our situation
dataset.drop("weight",axis=1,inplace=True)
dataset.columns

Index(['gender', 'age', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'time_in_hospital', 'payer_code',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'med_spec',
       'readmitted_final'],
      dtype='object')

In [45]:
dataset.groupby('age').size()

age
[0-10)        160
[10-20)       690
[20-30)      1649
[30-40)      3764
[40-50)      9607
[50-60)     17060
[60-70)     22059
[70-80)     25331
[80-90)     16434
[90-100)     2589
dtype: int64

# Encoding

In [46]:
for c in list(dataset.columns):
    
    # get a list of unique values
    n = dataset[c].unique()
    
    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(n)<30:
        print(c)
        print(n)
    else:
        print(c + ': ' +str(len(n)) + ' unique values')

gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
admission_type_id
[6 1 2 3 4 5 8 7]
discharge_disposition_id
[25  1  3  6  2  5  7 10  4 18  8 12 16 17 22 23  9 15 24 28 27]
admission_source_id
[ 1  7  2  4  5 20  6  3 17  8  9 14 10 22 11 25 13]
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
payer_code
['UNK' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM' 'CM' 'CH' 'PO' 'WC'
 'OT' 'OG' 'MP' 'FR']
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient
[ 0  1  2  3  6  5  4  7  9  8 15 10 11 14 12 13 17 16 21 18 19]
diag_1: 676 unique values
diag_2: 672 unique values
diag_3: 694 unique values
number_diagnoses
[ 1  9  6  7  5  8  3  4  2 16 12 13 15 10 11 14]
max_glu_serum
['None' '>300' 'Norm' '>200']
A1Cresult
['None' '>7' '>8' 'Norm']
metf

In [47]:
dataset.shape

(99343, 44)

In [48]:
dataset

gender      age  admission_type_id  discharge_disposition_id  \
0       Female   [0-10)                  6                        25   
1       Female  [10-20)                  1                         1   
2       Female  [20-30)                  1                         1   
3         Male  [30-40)                  1                         1   
4         Male  [40-50)                  1                         1   
...        ...      ...                ...                       ...   
101761    Male  [70-80)                  1                         3   
101762  Female  [80-90)                  1                         4   
101763    Male  [70-80)                  1                         1   
101764  Female  [80-90)                  2                         3   
101765    Male  [70-80)                  1                         1   

        admission_source_id  time_in_hospital payer_code  num_lab_procedures  \
0                         1                 1        UNK                  41   
1                         7                 3        UNK                  59   
2                         7                 2        UNK                  11   
3                         7                 2        UNK                  44   
4                         7                 1        UNK                  51   
...                     ...               ...        ...                 ...   
101761                    7                 3         MC                  51   
101762                    5                 5         MC                  33   
101763                    7                 1         MC                  53   
101764                    7                10         MC                  45   
101765                    7                 6        UNK                  13   

        num_procedures  num_medications  ...  insulin  glyburide-metformin  \
0                    0                1  ...       No                   No   
1                    0               18  ...       Up                   No   
2                    5               13  ...       No                   No   
3                    1               16  ...       Up                   No   
4                    0                8  ...   Steady                   No   
...                ...              ...  ...      ...                  ...   
101761               0               16  ...     Down                   No   
101762               3               18  ...   Steady                   No   
101763               0                9  ...     Down                   No   
101764               2               21  ...       Up                   No   
101765               3                3  ...       No                   No   

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No   
1                        No                        No   
2                        No                        No   
3                        No                        No   
4                        No                        No   
...                     ...                       ...   
101761                   No                        No   
101762                   No                        No   
101763                   No                        No   
101764                   No                        No   
101765                   No                        No   

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No   
1                            No                      No      Ch         Yes   
2                            No                      No      No         Yes   
3                            No                      No      Ch         Yes   
4                            No                      No      Ch         Yes   
...                         ...                     ...     ...         ...   
101761 

In [49]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [51]:
dataset.shape

(99343, 44)

In [52]:
x=dataset.iloc[:,0:43].values
x

array([['Female', '[0-10)', 6, ..., 'No', 'No', 'Other'],
       ['Female', '[10-20)', 1, ..., 'Ch', 'Yes', 'UNK'],
       ['Female', '[20-30)', 1, ..., 'No', 'Yes', 'UNK'],
       ...,
       ['Male', '[70-80)', 1, ..., 'Ch', 'Yes', 'UNK'],
       ['Female', '[80-90)', 2, ..., 'Ch', 'Yes', 'Surgery-General'],
       ['Male', '[70-80)', 1, ..., 'No', 'No', 'UNK']], dtype=object)

In [53]:
y=dataset.iloc[:,-1].values
y

array(['NO', 'YES', 'NO', ..., 'NO', 'NO', 'NO'], dtype=object)

In [54]:
ct=ColumnTransformer([("on", OneHotEncoder(), [0,1,6,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])], remainder = "passthrough")
x=ct.fit_transform(x)
x

<99343x2176 sparse matrix of type '<class 'numpy.float64'>'
	with 3988582 stored elements in Compressed Sparse Row format>

In [55]:
y=lb.fit_transform(y)
y

array([0, 1, 0, ..., 0, 0, 0])

# Splitting Data into Train and Test

In [56]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [57]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [58]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [59]:
y_pred=knn.predict(x_test)
y_pred

array([0, 1, 1, ..., 1, 1, 0])

In [60]:
y_test

array([1, 0, 0, ..., 1, 1, 1])

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.5644471286929388

In [62]:
import joblib
joblib.dump(knn,'multi.save')

['multi.save']

In [63]:
joblib.dump(ct,'xtransform')

['xtransform']